POST http://localhost:3000/api/product/create
content-type: application/json

{
	"image": "1.png",
	"title": "hello",
	"price": 12,
	"oldPrice": 12,
	"credit": 12,
	"description": "hello",
	"advantages": "hello",
	"disAdvantages": "3",
	"categories": ["apple"],
	"tags": ["tag - 1"],
	"characteristics": [{
		"name": "first",
		"value": "3"
	},
	{
		"name": "first",
		"value": "3"
	}]
}

###

GET http://localhost:3000/api/product/624b41651c82b2bd0ab72b07
content-type: application/json


###

POST http://localhost:3000/api/product/find
content-type: application/json

{
	 "limit": 5,
	 "category": "phone"
}