POST http://localhost:3000/api/product/create
content-type: application/json

{
	"image": "1.png",
	"title": "hello",
	"price": 12,
	"oldPrice": 12,
	"credit": 12,
	"description": "hello",
	"advantages": "hello",
	"disAdvantages": "3",
	"categories": ["apple"],
	"tags": ["tag - 1"],
	"characteristics": [{
		"name": "first",
		"value": "3"
	},
	{
		"name": "first",
		"value": "3"
	}]
}

###

GET http://localhost:3000/api/product/624b2c2eec4a93d2b119bf24
content-type: application/json
