version: '3'
services:
  top.api:
    image: top-api:latest
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    network_mode: host
    volumes:
      - ./.env:/opt/app/.env

  mongo-dev:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    command: --wiredTigerCacheSizeGB 1.5
    ports:
      - 27017:27017
    network_mode: host

  mongo-express-dev:
    image: mongo-express
    restart: always
    ports:
      - 3001:3001
    network_mode: host
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@127.0.0.1:27017/
